blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/<your-username>/<your-repo>/discussions
    about: Ask questions, share ideas, or discuss usage.
